In [1]:
import selenium
import time
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException 
from selenium import webdriver

from tqdm import tqdm # beautify loop
import pandas as pd # dataframe things

C:\Users\farras\AppData\Roaming\Python\Python38\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\farras\AppData\Roaming\Python\Python38\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\farras\AppData\Roaming\Python\Python38\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [4]:
#Inisiasi 
s=Service('C:/SAINS DATA/chromedriver.exe')
options = webdriver.ChromeOptions()
options.add_experimental_option("detach", True)
options.add_argument('disable_infobars')

driver = webdriver.Chrome(service=s, options=options)
url="https://sinta.kemdikbud.go.id/authors"

driver.get(url)
# driver.maximize_window()

SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 107
Current browser version is 110.0.5481.104 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
	Ordinal0 [0x00EFACD3+2075859]
	Ordinal0 [0x00E8EE61+1633889]
	Ordinal0 [0x00D8B7BD+571325]
	Ordinal0 [0x00DADFCD+712653]
	Ordinal0 [0x00DA9266+692838]
	Ordinal0 [0x00DA6BE9+682985]
	Ordinal0 [0x00DDDBD3+908243]
	Ordinal0 [0x00DDD6AA+906922]
	Ordinal0 [0x00DD7136+880950]
	Ordinal0 [0x00DAFEFD+720637]
	Ordinal0 [0x00DB0F3F+724799]
	GetHandleVerifier [0x011AEED2+2769538]
	GetHandleVerifier [0x011A0D95+2711877]
	GetHandleVerifier [0x00F8A03A+521194]
	GetHandleVerifier [0x00F88DA0+516432]
	Ordinal0 [0x00E9682C+1665068]
	Ordinal0 [0x00E9B128+1683752]
	Ordinal0 [0x00E9B215+1683989]
	Ordinal0 [0x00EA6484+1729668]
	BaseThreadInitThunk [0x76A46BD9+25]
	RtlGetFullPathName_UEx [0x779C8FD2+1218]
	RtlGetFullPathName_UEx [0x779C8F9D+1165]

In [4]:
df = pd.read_excel('Data Author-FULL.xlsx')
df

,Nama,Universitas,Department,Id Sinta,SINTA Score 3Yr,SINTA Score Overall,Subject 1,subject-list href 1,Subject 2,subject-list href 2,Subject 3,subject-list href 3,Subject 4,subject-list href 4,Subject 5,subject-list href 5,Scopus H-index,Wos H-index,Google Scholar H-index,Unnamed: 19
0,DODI YULI SATRIA,Akademi Akuntansi (AKTAN) Boekittinggi,Akuntansi (D3),6732361,NaN,2,Accounting,https://sinta.kemdikbud.go.id/subjects/detail/...,Financial,https://sinta.kemdikbud.go.id/subjects/detail/...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,1,NaN
1,MURNI HAYATI,Akademi Akuntansi (AKTAN) Boekittinggi,Akuntansi (D3),6661122,NaN,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,2,NaN
2,LINDA FITRIYANTI,Akademi Akuntansi Borobudur,Akuntansi (D3),6697649,NaN,1,umum,https://sinta.kemdikbud.go.id/subjects/detail/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,RINNY YUDOWATIBOROBUDUR,Akademi Akuntansi Borobudur,Akuntansi (D3),6689024,NaN,4,Economic,https://sinta.kemdikbud.go.id/subjects/detail/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,1,NaN
4,SUHIKMAT,Akademi Akuntansi Borobudur,Akuntansi (D3),6701790,NaN,5,Akuntansi,https://sinta.kemdikbud.go.id/subjects/detail/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249579,ZURAYYA FADILA,NaN,Kedokteran (S1),6763491,NaN,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249580,ZURLINA LUBIS,NaN,Manajemen (S1),6785320,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
249581,ZUSMA WIDAWATY A WAHAB,NaN,Akuntansi (D3),6043207,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249582,ZUUL FITRIANI UMARI,NaN,Manajemen Zakat dan Wakaf (S1),6673689,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
249583,ZUYYINA FIHAYATI,NaN,Unknown,5987741,NaN,9,kedokteran,https://sinta.kemdikbud.go.id/subjects/detail/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,1,NaN

In [15]:
# df.iloc[df['Nama'] == "A IND'AH CAMELIA", :]
# df.loc[df['Nama'] == "ZULFAYANDI PAWANIS", :]
# 70764
# 72796

# the name that we use for keyword
data_nama = list(df.iloc[70764:72797, 0])
data_nama[:5]

["A IND'AH CAMELIA",
 'A RETNO PUDJI RAHAYU',
 'A SHOFY MUBARAK',
 'A. SYIFAUL QULUB',
 'ABD AZIZ']

In [19]:
sinta_dict = {'Nama' : [], 
              'Universitas' : [],
              'Department' : [],
              'SINTA Score 3Yr' : [],
              'SINTA Score Overall' : [], 
              'Subject 1' : [], 
              'Subject 2' : [], 
              'Subject 3' : [], 
              'Subject 4' : [], 
              'Subject 5' : [], 
              'Index 1' : [], 
              'Index 2' : [], 
              'Index 3' : []
              }

## Scraping

In [21]:
for i in tqdm(data_nama):    # iterate through all names
    search = driver.find_element(By.NAME, 'q')      # locate search box
    search.clear()      # clear searchbox
    search.send_keys(i) # input names to searchbox
    search.send_keys(Keys.ENTER) # enter
    time.sleep(0.2) # freeze for a moment

    parent = driver.find_elements(By.CSS_SELECTOR, 'div[class = "list-item row mb-4"]') # locate element parent
    for subparent in parent:
        campus = subparent.find_element(By.CLASS_NAME, 'profile-affil').text # locate university
        if campus == 'Universitas Airlangga': # filter: unair
            sinta_dict['Universitas'].append(campus) 
            
            name = subparent.find_element(By.CLASS_NAME, 'profile-name').text # locate name
            sinta_dict['Nama'].append(name)
            
            prodi = subparent.find_element(By.CSS_SELECTOR, 'div[class = "profile-dept"]').text # locate department
            sinta_dict['Department'].append(prodi)
            
            sinta_score = subparent.find_elements(By.CLASS_NAME, 'pr-num') # locate scores
            sinta_dict['SINTA Score 3Yr'].append(sinta_score[0].text)
            sinta_dict['SINTA Score Overall'].append(sinta_score[-1].text)
            
            subjects = subparent.find_elements(By.TAG_NAME, 'li') # locate subjects
            for i in range(5):
                try:
                    sinta_dict[f'Subject {i+1}'].append(subjects[i].text)
                except IndexError: 
                    sinta_dict[f'Subject {i+1}'].append(None) #if the subject <= 5, fill the list with none
            
            table = subparent.find_elements(By.TAG_NAME, 'td') # locate index
            table_only_int = table[2::3]
            for i in range(3):
                sinta_dict[f'Index {i+1}'].append(int(table_only_int[i].text))

100%|██████████| 2033/2033 [1:05:40<00:00,  1.94s/it]

In [22]:
# as dataframe
sinta_df = pd.DataFrame(sinta_dict)
sinta_df

,Nama,Universitas,Department,SINTA Score 3Yr,SINTA Score Overall,Subject 1,Subject 2,Subject 3,Subject 4,Subject 5,Index 1,Index 2,Index 3
0,A RETNO PUDJI RAHAYU,Universitas Airlangga,Ilmu Kedokteran Gigi (S3),442,1.214,Oral and Maxillofacial Pathology,None,None,None,None,7,0,10
1,A SHOFY MUBARAK,Universitas Airlangga,Bioteknologi Perikanan dan Kelautan (S2),630,1.009,live feed,None,None,None,None,3,1,14
2,ABD AZIZ,Universitas Airlangga,Unknown,37,37,Science,Environmental Science,None,None,None,0,0,0
3,ABD NASIR,Universitas Airlangga,Keperawatan (D3),272,447,Keperawatan,None,None,None,None,2,1,9
4,ABDUL HADI FURQONI,Universitas Airlangga,Unknown,109,147,Forensic science,None,None,None,None,2,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013,ZAYYIN DINANA,Universitas Airlangga,Unknown,135,190,Researcher,None,None,None,None,4,0,5
2014,ZENDY WULAN AYU WIDHI P,Universitas Airlangga,Ilmu Hukum (S1),76,128,Human Right,Children Right,Constitutional Law,Citizenship Law,None,0,0,4
2015,ZIDA HUSNINA,Universitas Airlangga,Kesehatan Masyarakat (S1),115,172,Epidemiology and Environmental health,None,None,None,None,1,1,2
2016,ZIKRI FATHUR RAHMAN,Universitas Airlangga,Unknown,149,152,Occupational Health and Safety,Hygine Industry,Safety Industry,Public Health,None,1,0,0
2017,ZULFAYANDI PAWANIS,Universitas Airlangga,Unknown,130,245,Cardiovascular Surgery,None,None,None,None,3,0,5

In [25]:
sinta_df.drop_duplicates()

,Nama,Universitas,Department,SINTA Score 3Yr,SINTA Score Overall,Subject 1,Subject 2,Subject 3,Subject 4,Subject 5,Index 1,Index 2,Index 3
0,A RETNO PUDJI RAHAYU,Universitas Airlangga,Ilmu Kedokteran Gigi (S3),442,1.214,Oral and Maxillofacial Pathology,None,None,None,None,7,0,10
1,A SHOFY MUBARAK,Universitas Airlangga,Bioteknologi Perikanan dan Kelautan (S2),630,1.009,live feed,None,None,None,None,3,1,14
2,ABD AZIZ,Universitas Airlangga,Unknown,37,37,Science,Environmental Science,None,None,None,0,0,0
3,ABD NASIR,Universitas Airlangga,Keperawatan (D3),272,447,Keperawatan,None,None,None,None,2,1,9
4,ABDUL HADI FURQONI,Universitas Airlangga,Unknown,109,147,Forensic science,None,None,None,None,2,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013,ZAYYIN DINANA,Universitas Airlangga,Unknown,135,190,Researcher,None,None,None,None,4,0,5
2014,ZENDY WULAN AYU WIDHI P,Universitas Airlangga,Ilmu Hukum (S1),76,128,Human Right,Children Right,Constitutional Law,Citizenship Law,None,0,0,4
2015,ZIDA HUSNINA,Universitas Airlangga,Kesehatan Masyarakat (S1),115,172,Epidemiology and Environmental health,None,None,None,None,1,1,2
2016,ZIKRI FATHUR RAHMAN,Universitas Airlangga,Unknown,149,152,Occupational Health and Safety,Hygine Industry,Safety Industry,Public Health,None,1,0,0
2017,ZULFAYANDI PAWANIS,Universitas Airlangga,Unknown,130,245,Cardiovascular Surgery,None,None,None,None,3,0,5

In [26]:
sinta_df.to_excel('sinta_scraped_no_duplicate.xlsx')
print('done!')

done!

In [33]:
# Jumlah data yg berbeda
len(list(set(data_nama) - set(sinta_df['Nama'])))
# list(set(data_nama) - set(sinta_df['Nama']))[:20]

70

## Coba

In [6]:
unair = driver.find_element(By.CLASS_NAME, 'profile-affil')
unair.text

'Universitas Airlangga'

In [5]:
sinta_score = driver.find_element(By.CLASS_NAME, 'pr-num')
sinta_score.text

'195'